SELECT CUSTOMER.NAME, PRODUCT.DESCRIPTION
FROM PURCHASE_ORDER,
     PRODUCT,
     MANUFACTURER,
     CUSTOMER
WHERE PURCHASE_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
  AND PRODUCT.MANUFACTURER_ID = MANUFACTURER.MANUFACTURER_ID
  AND PURCHASE_ORDER.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
  AND MANUFACTURER.CITY LIKE 'san%'
ORDER BY CUSTOMER.NAME;